exclude: '.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']
      - id: requirements-txt-fixer


  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--ignore=E501,W503,E121,E402,E126,F401"]
        additional_dependencies: [flake8-isort, flake8-tidy-imports]
  - repo: https://github.com/psf/black
    rev: 21.6b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
      - id: python-bandit-vulnerability-check
        args: [ -lll, --recursive, ./ctix ]
        files: .py$
